{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(506, 13)\n",
      "MSE: nan(nan)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/wangjiabin/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    }
   ],
   "source": [
    "from pandas import read_csv\n",
    "from sklearn.model_selection import KFold, cross_val_score #, LogisticRegression\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "filename ='/Users/wangjiabin/ML_2020_summer/<ml with python practice>/chap_11_metric_for _algorithm_evaluation/housing.csv'\n",
    "names =['RRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','RATATIO','B','LATAT','MEDV']\n",
    "data = read_csv(filename, names =names,delim_whitespace =True)\n",
    "#deliml_whitespace: If this option is set to True, nothing should be passed in for the delimiter parameter.\n",
    "array =data.values\n",
    "X = array[:,0:13]\n",
    "Y = array[:,13]\n",
    "n_splits =10\n",
    "seed = 7\n",
    "print(X.shape)\n",
    "kfold =KFold(n_splits =n_splits,shuffle =True, random_state = seed)\n",
    "model = LogisticRegression(solver='lbfgs',max_iter=999)\n",
    "scoring = 'neg_mean_squared_error'\n",
    "result = cross_val_score(model, X,Y, cv =kfold, scoring = scoring)\n",
    "print('MSE: %.3f(%.3f)'% (result.mean(),result.std()))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
